# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

auto: true
markdown: rdiscount
permalink: pretty
pygments: true
safe: true
server: true

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: John Doe
author_email: john@doe.com
title: Jekyll Zurb Quickstart
url: http://www.example.com
